"""
Install a pre-commit git hook that runs smoke tests before each commit.

Usage (from any project root):
    python <path_to>/install_precommit.py

This creates .git/hooks/pre-commit that runs:
    python -m pytest tests/test_smoke.py -x -q --tb=line
If tests fail, the commit is aborted.
"""
import sys
import stat
from pathlib import Path

HOOK_SCRIPT = """\
#!/bin/sh
# Auto-generated by Github_Brain/agents/testing-agent/install_precommit.py
# Runs smoke tests before every commit. Abort if any fail.

echo "Running smoke tests..."
python -m pytest tests/test_smoke.py -x -q --tb=line 2>&1
status=$?

if [ $status -ne 0 ]; then
    echo ""
    echo "COMMIT BLOCKED: Smoke tests failed. Fix before committing."
    exit 1
fi

echo "Smoke tests passed."
exit 0
"""


def install(project_path: Path = None):
    project_path = project_path or Path.cwd()
    git_dir = project_path / ".git"
    if not git_dir.exists():
        print(f"ERROR: No .git directory in {project_path}")
        sys.exit(1)

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)

    hook_file = hooks_dir / "pre-commit"
    if hook_file.exists():
        print(f"WARNING: {hook_file} already exists. Overwriting.")

    hook_file.write_text(HOOK_SCRIPT, encoding="utf-8", newline="\n")
    # Make executable
    hook_file.chmod(hook_file.stat().st_mode | stat.S_IEXEC)
    print(f"Installed pre-commit hook: {hook_file}")
    print("Smoke tests will run before every commit.")


if __name__ == "__main__":
    path = Path(sys.argv[1]).resolve() if len(sys.argv) > 1 else Path.cwd()
    install(path)
